### ISSUE TITLE
create multiple styles for the documentation using jinja

### ISSUE THREAD

**Issue by AirinB** [MLH-Fellowship/Rubicon#8]
Why we need this? 
We are creating 2 basic templates which will later be used in our back end. Basically, when the user writes documentation, it will look like a regular note taking app, but on the back end we will convert the notes into the jinja template so that the user can later export it etc.

Deya finished her template which includes: 

- [x] basic styling with boostrap & css
- [x] tests out the syntax of Jinja

Ana is working on her template which includes:
- [x] basic styling with boostrap & css
- [x] tables
- [x] highlighting (going to make the code highlight api in the extension) 
- [x] images
- [x] links
- [x] styles

**Comment by gmelodie** [comment]
Nit: include a list of possible templates on the issue's description
